abstract: generate HTML pagination linkage easily.
name: CGI-Pager
author: 'Egor Shipovalov, http://pragmaticware.com/'
build_requires:
  Test::More: 0.42
distribution_type: module
license: perl
installdirs: site
version_from: perl_lib/CGI/Pager.pm
no_index:
  directory:
    - inc
    - t
requires:
  URI: 0
  URI::QueryParam: 0
  perl: 5.8.0
